[build]
  command = 'npm run build'
  publish = 'dist'

const EMAILJS_SERVICE_ID = "service_xxxxxxx"; // Your actual service ID
const EMAILJS_TEMPLATE_ID = "template_xxxxxxx"; // Your actual template ID
const EMAILJS_PUBLIC_KEY = "xxxxxxxxxxxxxxx"; // Your actual public key